version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 10
    environment:
      # 시크릿 환경 변수 추가
      DUCKIE_GPG_PASSWORD: ${{ secrets.DUCKIE_GPG_PASSWORD }}
      DUCKIE_ADMINISTRATOR_GITHUB_TOKEN: ${{ secrets.DUCKIE_ADMINISTRATOR_GITHUB_TOKEN }}
      DUCKIE_ADMINISTRATOR_EMAIL: ${{ secrets.DUCKIE_ADMINISTRATOR_EMAIL }}
      DUCKIE_ADMINISTRATOR_USER_NAME: ${{ secrets.DUCKIE_ADMINISTRATOR_USER_NAME }}
      DUCKIE_VERSION_CODE_RELATIVE_PATH: ${{ secrets.DUCKIE_VERSION_CODE_RELATIVE_PATH }}
      DUCKIE_SIGNING_KEY_BASE_64: ${{ secrets.DUCKIE_SIGNING_KEY_BASE_64 }}
      DUCKIE_SIGNING_KEY_ALIAS: ${{ secrets.DUCKIE_SIGNING_KEY_ALIAS }}
      DUCKIE_SIGNING_STORE_PASSWORD: ${{ secrets.DUCKIE_SIGNING_STORE_PASSWORD }}
      DUCKIE_SIGNING_KEY_PASSWORD: ${{ secrets.DUCKIE_SIGNING_KEY_PASSWORD }}
      DUCKIE_FIREBASE_APP_ID: ${{ secrets.DUCKIE_FIREBASE_APP_ID }}
      DUCKIE_FIREBASE_CREDENTIAL_FILE_CONTENT: ${{ secrets.DUCKIE_FIREBASE_CREDENTIAL_FILE_CONTENT }}
    # Dependabot에서 환경 변수 사용
    command: |
      env DUCKIE_GPG_PASSWORD=$DUCKIE_GPG_PASSWORD /usr/bin/python3 /path/to/dependabot-script.py |
      env DUCKIE_ADMINISTRATOR_GITHUB_TOKEN=$DUCKIE_ADMINISTRATOR_GITHUB_TOKEN /usr/bin/python3 /path/to/dependabot-script.py |
      env DUCKIE_ADMINISTRATOR_EMAIL=$DUCKIE_ADMINISTRATOR_EMAIL /usr/bin/python3 /path/to/dependabot-script.py |
      env DUCKIE_ADMINISTRATOR_USER_NAME=$DUCKIE_ADMINISTRATOR_USER_NAME /usr/bin/python3 /path/to/dependabot-script.py |
      env DUCKIE_VERSION_CODE_RELATIVE_PATH=$DUCKIE_VERSION_CODE_RELATIVE_PATH /usr/bin/python3 /path/to/dependabot-script.py |
      env DUCKIE_SIGNING_KEY_BASE_64=$DUCKIE_SIGNING_KEY_BASE_64 /usr/bin/python3 /path/to/dependabot-script.py |
      env DUCKIE_SIGNING_KEY_ALIAS=$DUCKIE_SIGNING_KEY_ALIAS /usr/bin/python3 /path/to/dependabot-script.py |
      env DUCKIE_SIGNING_STORE_PASSWORD=$DUCKIE_SIGNING_STORE_PASSWORD /usr/bin/python3 /path/to/dependabot-script.py |
      env DUCKIE_SIGNING_KEY_PASSWORD=$DUCKIE_SIGNING_KEY_PASSWORD /usr/bin/python3 /path/to/dependabot-script.py |
      env DUCKIE_FIREBASE_APP_ID=$DUCKIE_FIREBASE_APP_ID /usr/bin/python3 /path/to/dependabot-script.py |
      env DUCKIE_FIREBASE_CREDENTIAL_FILE_CONTENT=$DUCKIE_FIREBASE_CREDENTIAL_FILE_CONTENT /usr/bin/python3 /path/to/dependabot-script.py
      
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 10
