version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 10
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 10
