[versions]
# plugins
dokka = "1.7.20"
ktlint-gradle = "11.0.0"
# https://github.com/JLLeitschuh/ktlint-gradle/issues/589
# klint 최신 버전과 사용 불가
ktlint-source = "0.45.2"
detekt = "1.21.0"
paparazzi = "1.1.0"
ksp = "1.7.20-1.0.8"
gradle-maven-publish = "0.22.0"

# build
gradle-agp = "8.0.0-alpha08"
kotlin-core = "1.7.20"
kotlin-metadata = "0.5.0"
oss-license-plugin = "0.10.5"

# compose
compose-core = "1.2.1"
compose-compiler = "1.3.2"
compose-material3 = "1.0.1"
compose-activity = "1.6.1"
compose-constraintlayout = "1.0.1"
compose-reference-suppressor = "1.0.5"
coil = "2.2.2"

# tools
kover = "0.6.1"
lint = "30.3.1"
logeukes = "1.0.0"
ktx-core = "1.9.0"
systemuicontroller = "1.0.1"
profileinstaller = "1.2.0"
customview-poolingcontainer = "1.0.0"
kotlin-api-validation = "0.12.1"
kotlin-collections-immutable = "0.3.5"
oss-license-library = "17.0.0"
gfm-dsl = "1.0.0"

# androidx
androidx-appcompat = "1.5.1" # needs for oss license activity
androidx-splash = "1.0.0"
androidx-datastore = "1.0.0"
androidx-junit = "1.1.4"
androidx-benchmark = "1.1.1"

# test
junit = "4.13.2"
junit-engine = "5.9.1"
test-parameter-injector = "1.10"

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
gradle-maven-publish-core = { id = "com.vanniktech.maven.publish", version.ref = "gradle-maven-publish" }
gradle-maven-publish-base = { id = "com.vanniktech.maven.publish.base", version.ref = "gradle-maven-publish" }
oss-license = { id = "com.google.android.gms.oss-licenses-plugin", version.ref = "oss-license-plugin" }
kotlin-api-validation = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlin-api-validation" }

[libraries]
build-dokka-base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka" }
build-dokka-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
build-gradle-agp = { module = "com.android.tools.build:gradle", version.ref = "gradle-agp" }
build-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-core" }
build-kover = { module = "org.jetbrains.kotlinx:kover", version.ref = "kover" }
build-oss-license = { module = "com.google.android.gms:oss-licenses-plugin", version.ref = "oss-license-plugin" }
build-gradle-maven-publish-core = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "gradle-maven-publish" }

ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-core" }
kotlin-metadata = { module = "org.jetbrains.kotlinx:kotlinx-metadata-jvm", version.ref = "kotlin-metadata" }
kotlin-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlin-collections-immutable" }

compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose-core" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-core" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-core" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "compose-constraintlayout" }
compose-coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-core" } # debugImplementation
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-core" }
compose-reference-suppressor = { module = "land.sungbin:composable.reference.suppressor.plugin", version.ref = "compose-reference-suppressor" }

customview-poolingcontainer = { module = "androidx.customview:customview-poolingcontainer", version.ref = "customview-poolingcontainer" } # debugImplementation

lint-core = { module = "com.android.tools.lint:lint", version.ref = "lint" }
lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" } # compileOnly

ktx-core = { module = "androidx.core:core-ktx", version.ref = "ktx-core" }

util-gfm-dsl = { module = "land.sungbin.gfm:gfm-dsl", version.ref = "gfm-dsl" }
util-oss-license = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "oss-license-library" }
util-logeukes = { module = "land.sungbin:logeukes", version.ref = "logeukes" }
util-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }
util-systemuicontroller = { module = "land.sungbin:systemuicontroller", version.ref = "systemuicontroller" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-splash = { module = "androidx.core:core-splashscreen", version.ref = "androidx-splash" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-benchmark = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidx-benchmark" }

test-parameter-injector = { module = "com.google.testparameterinjector:test-parameter-injector", version.ref = "test-parameter-injector" }
test-lint = { module = "com.android.tools.lint:lint-tests", version.ref = "lint" }
test-junit-core = { module = "junit:junit", version.ref = "junit" }
test-junit-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit-engine" } # testRuntimeOnly
test-compose-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-core" } # debugImplementation
test-compose-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-core" } # androidTestImplementation

[bundles]
test-lint = ["lint-core", "test-lint"]
compose-core = ["compose-foundation", "compose-activity", "compose-tooling-preview"]
compose-debug = ["compose-tooling", "customview-poolingcontainer"] # debugImplementation
benchmark = ["androidx-junit", "androidx-benchmark"]
