# ref: https://dev.to/supersuman/build-and-sign-android-apps-using-github-actions-54j
name: Android CD TEST

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false"
on:
  push:
    tags:
      - v*
      - github_action_test_*

jobs:
  cd-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/heads/develop
          create-branch: true
          token: ${{ secrets.DUCKIE_ADMINISTRATOR_GITHUB_TOKEN }}

      - name: Set Config
        run: |
          git config --local user.email "ridickle7@gmail.com"
          git config --local user.name "ricky_0_k"

      - name: Increase versionCode
        run: |
          # 특정 경로의 파일 내에서 특정 패턴이 포함된 라인의 숫자값을 가져옴
          versionCode=$(grep 'const val versionCode =' ${{ secrets.DUCKIE_VERSION_CODE_RELATIVE_PATH }} | sed 's/[^0-9]*//g')

          # 숫자로 바꾸고 1을 더한 값으로 업데이트
          versionCode=$((versionCode + 1))

          # sed를 사용하여 파일 내 해당 라인 업데이트
          sed -i "s/const val versionCode = .*/const val versionCode = $versionCode/" ./${{ secrets.DUCKIE_VERSION_CODE_RELATIVE_PATH }}

      - name: Commit changes
        run: |
          # 특정 경로의 파일 내에서 특정 패턴이 포함된 라인의 숫자값을 가져옴
          versionCode=$(grep 'const val versionCode =' ${{ secrets.DUCKIE_VERSION_CODE_RELATIVE_PATH }} | sed 's/[^0-9]*//g')
          git add .
          git commit -m "veresionCode $versionCode 으로 올리기"

      - name: Push changes
        run: |
          git push
